exec-once = waybar
exec-once = mako
exec-once = swww-daemon
exec-once = swayosd-server
exec-once = bash -c 'if [ -f ~/Pictures/Wallpapers/default.jpg ]; then swww img ~/Pictures/Wallpapers/default.jpg; fi'